# Generated by Django 4.1.6 on 2023-02-07 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('in_prof', models.BooleanField(default=False, verbose_name='in_prof')),
                ('out_prof', models.BooleanField(default=False, verbose_name='out_prof')),
                ('cn_std', models.BooleanField(default=False, verbose_name='cn_std')),
                ('ee_std', models.BooleanField(default=False, verbose_name='ee_std')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
