# Generated by Django 4.1.6 on 2023-04-02 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import website.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoorPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('file', models.FileField(null=True, upload_to=website.utils.file_path)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField(null=True)),
                ('Bplus', models.IntegerField(null=True)),
                ('B', models.IntegerField(null=True)),
                ('Cplus', models.IntegerField(null=True)),
                ('C', models.IntegerField(null=True)),
                ('Dplus', models.IntegerField(null=True)),
                ('D', models.IntegerField(null=True)),
                ('F', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('in_prof', models.BooleanField(default=False, verbose_name='in_prof')),
                ('out_prof', models.BooleanField(default=False, verbose_name='out_prof')),
                ('cn_std', models.BooleanField(default=False, verbose_name='cn_std')),
                ('ee_std', models.BooleanField(default=False, verbose_name='ee_std')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('major', models.CharField(choices=[('ไฟฟ้า', 'ไฟฟ้า'), ('คอมพิวเตอร์', 'คอมพิวเตอร์')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StdPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('list', models.CharField(max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='StdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=100, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('major', models.CharField(choices=[('ไฟฟ้า', 'ไฟฟ้า'), ('คอมพิวเตอร์', 'คอมพิวเตอร์')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thainame', models.CharField(max_length=100, null=True)),
                ('engname', models.CharField(max_length=100, null=True)),
                ('detail', models.CharField(max_length=500, null=True)),
                ('committee', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ยังไม่มีนักศึกษาลงทะเบียน', 'ยังไม่มีนักศึกษาลงทะเบียน'), ('รอการอนุมัติ', 'รอการอนุมัติ'), ('อนุมัติ', 'อนุมัติ')], default='ยังไม่มีนักศึกษาลงทะเบียน', max_length=200, null=True)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profmodel')),
                ('student1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='website.stdmodel')),
                ('student2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='website.stdmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Docproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('preliminary', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('progress1', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('progress2', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('draftthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('finalthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profmodel')),
            ],
        ),
    ]
