# Generated by Django 4.1.6 on 2023-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='consult',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
