# Generated by Django 4.1.6 on 2023-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docproject',
            name='date_draftthesis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docproject',
            name='date_finalthesis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docproject',
            name='date_preliminary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docproject',
            name='date_progress1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docproject',
            name='date_progress2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docproject',
            name='date_proposal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
