# Generated by Django 4.1.5 on 2023-04-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='com1sc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='com2sc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='consc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
