# Generated by Django 4.1.5 on 2023-04-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_scoremodel_grade_scoremodel_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complanmodel',
            name='list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coorplanmodel',
            name='list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docmodel',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profplanmodel',
            name='list',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdplanmodel',
            name='list',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
