# Generated by Django 4.1.6 on 2023-02-08 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_docmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='docmodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
