# Generated by Django 4.1.6 on 2023-04-05 08:16

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_fileproject_delete_docproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(default=website.models.SubjectModel.current_year, null=True)),
                ('startterm', models.DateField(null=True)),
                ('endterm', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc1', models.IntegerField(blank=True, null=True)),
                ('sc2', models.IntegerField(blank=True, null=True)),
                ('sc3', models.IntegerField(blank=True, null=True)),
                ('sc4', models.IntegerField(blank=True, null=True)),
                ('sc5', models.IntegerField(blank=True, null=True)),
                ('sc6', models.IntegerField(blank=True, null=True)),
                ('sc7', models.IntegerField(blank=True, null=True)),
                ('sc8', models.IntegerField(blank=True, null=True)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profmodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
                ('std1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std1', to='website.stdmodel')),
                ('std2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std2', to='website.stdmodel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.subjectmodel')),
            ],
        ),
    ]
