# Generated by Django 4.1.6 on 2023-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_othermodel_user_profmodel_user_projectmodel_consult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField(null=True)),
                ('Bplus', models.IntegerField(null=True)),
                ('B', models.IntegerField(null=True)),
                ('Cplus', models.IntegerField(null=True)),
                ('C', models.IntegerField(null=True)),
                ('Dplus', models.IntegerField(null=True)),
                ('D', models.IntegerField(null=True)),
                ('F', models.IntegerField(null=True)),
            ],
        ),
    ]
