# Generated by Django 4.1.6 on 2023-04-02 09:29

from django.db import migrations, models
import django.db.models.deletion
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_docproject_date_draftthesis_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docproject',
            new_name='Docproject1',
        ),
        migrations.CreateModel(
            name='Docproject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress2', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('date_progress2', models.DateField(blank=True, null=True)),
                ('draftthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('date_draftthesis', models.DateField(blank=True, null=True)),
                ('finalthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('date_finalthesis', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
            ],
        ),
    ]
