# Generated by Django 4.1.6 on 2023-04-01 09:39

from django.db import migrations, models
import django.db.models.deletion
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_grademodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('preliminary', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('progress1', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('progress2', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('draftthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('finalthesis', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
            ],
        ),
    ]
