# Generated by Django 4.1.5 on 2023-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_scorecom1_sc1_alter_scorecom1_sc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproject',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='com1sc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='com2sc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='consc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
