# Generated by Django 4.1.6 on 2023-04-04 06:08

from django.db import migrations, models
import django.db.models.deletion
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_docproject_docproject1_docproject2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docproject1',
            name='date_draftthesis',
        ),
        migrations.RemoveField(
            model_name='docproject1',
            name='date_finalthesis',
        ),
        migrations.RemoveField(
            model_name='docproject1',
            name='date_progress2',
        ),
        migrations.RemoveField(
            model_name='docproject1',
            name='draftthesis',
        ),
        migrations.RemoveField(
            model_name='docproject1',
            name='finalthesis',
        ),
        migrations.RemoveField(
            model_name='docproject1',
            name='progress2',
        ),
        migrations.CreateModel(
            name='Fileproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('proposal', 'proposal'), ('preliminary', 'preliminary'), ('progress1', 'progress1'), ('progress2', 'progress2'), ('draftthesis', 'draftthesis'), ('finalthesis', 'finalthesis')], max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=website.utils.file_path)),
                ('date', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
            ],
        ),
    ]
