# Generated by Django 4.1.6 on 2023-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_othermodel_user_profmodel_user_stdmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stdmodel',
            name='user',
        ),
    ]
