# Generated by Django 4.1.5 on 2023-04-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_complanmodel_list_alter_coorplanmodel_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecom1',
            name='std1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std1sc1', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scorecom1',
            name='std2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std2sc1', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scorecom2',
            name='std1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std1sc2', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scorecom2',
            name='std2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std2sc2', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scoreconsult',
            name='std1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std1con', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scoreconsult',
            name='std2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std2con', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='std1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std1', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='std2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='std2', to='website.stdmodel'),
        ),
    ]
