# Generated by Django 4.1.6 on 2023-04-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_docproject1_date_draftthesis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileproject',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel'),
        ),
    ]
