# Generated by Django 4.1.7 on 2023-04-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_projectmodel_committee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='committee',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='committee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee1', to='website.profmodel'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='committee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee2', to='website.profmodel'),
        ),
    ]
