# Generated by Django 4.1.6 on 2023-03-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_othermodel_user_remove_profmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='student1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='student2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='website.stdmodel'),
        ),
    ]
