# Generated by Django 4.1.5 on 2023-04-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_fileproject_name_scoremodel_grade_scoremodel_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileproject',
            name='name',
        ),
    ]
