# Generated by Django 4.1.6 on 2023-02-08 08:39

from django.db import migrations, models
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_docmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=website.utils.file_path),
        ),
    ]
