# Generated by Django 4.1.5 on 2023-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_fileproject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
