# Generated by Django 4.1.7 on 2023-04-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_projectmodel_committee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topicproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('proposal', 'proposal'), ('preliminary', 'preliminary'), ('progress1', 'progress1'), ('progress2', 'progress2'), ('draftthesis', 'draftthesis'), ('finalthesis', 'finalthesis')], max_length=200, null=True)),
                ('datedue', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='grademodel',
            name='subject',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.subjectmodel'),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel'),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.topicproject'),
        ),
    ]
