# Generated by Django 4.1.5 on 2023-04-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_projectmodel_major_scoremodel_major'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComPlanModel',
        ),
    ]
