# Generated by Django 4.1.6 on 2023-04-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_fileproject_date_alter_fileproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docproject2',
            name='project',
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Docproject1',
        ),
        migrations.DeleteModel(
            name='Docproject2',
        ),
    ]
