# Generated by Django 4.1.7 on 2023-04-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_complanmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='cn_std',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='ee_std',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='in_prof',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='out_prof',
        ),
    ]
