# Generated by Django 4.1.7 on 2023-04-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_topicproject_grademodel_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicproject',
            name='datedue',
            field=models.DateField(null=True),
        ),
    ]
