# Generated by Django 4.1.6 on 2023-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_othermodel_user_alter_profmodel_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermodel',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='othermodel',
            old_name='lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='profmodel',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='profmodel',
            old_name='lname',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='stdmodel',
            old_name='fname',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='stdmodel',
            old_name='lname',
            new_name='Last_name',
        ),
    ]
