# Generated by Django 4.1.5 on 2023-04-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_scoremodel_sc1_remove_scoremodel_sc2_and_more'),
        ('website', '0007_alter_topicproject_datedue'),
    ]

    operations = [
    ]
