# Generated by Django 4.1.7 on 2023-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_newsmodel_cn_std_remove_newsmodel_ee_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicproject',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
