# Generated by Django 4.1.6 on 2023-03-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_fname_othermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermodel',
            old_name='First_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='othermodel',
            old_name='Last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='profmodel',
            old_name='First_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='profmodel',
            old_name='Last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='stdmodel',
            old_name='First_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='stdmodel',
            old_name='Last_name',
            new_name='lname',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='consult',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='student1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='website.stdmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='student2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='website.stdmodel'),
        ),
    ]
