# Generated by Django 4.1.6 on 2023-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profmodel',
            name='major',
            field=models.CharField(choices=[('ไฟฟ้า', 'ไฟฟ้า'), ('คอมพิวเตอร์', 'คอมพิวเตอร์')], max_length=100, null=True),
        ),
    ]
