# Generated by Django 4.1.7 on 2023-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_topicproject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicproject',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
