# Generated by Django 4.1.7 on 2023-04-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_topicproject_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicproject',
            name='score',
        ),
        migrations.CreateModel(
            name='ScoreTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.projectmodel')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.topicproject')),
            ],
        ),
    ]
