# Generated by Django 4.1.6 on 2023-02-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_othermodel_alter_profmodel_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdid', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว')], max_length=100, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('major', models.CharField(choices=[('ไฟฟ้า', 'ไฟฟ้า'), ('คอมพิวเตอร์', 'คอมพิวเตอร์')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
