# Generated by Django 4.1.6 on 2023-03-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_projectmodel_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='consult',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
