# Generated by Django 4.1.7 on 2023-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_topicproject_score_scoretopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproject',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScoreTopic',
        ),
    ]
