# Generated by Django 4.1.7 on 2023-04-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_scorecom1_topic_scorecom2_topic_scoreconsult_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproject',
            name='sccom1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileproject',
            name='sccom2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileproject',
            name='sccon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
