# Generated by Django 4.1.7 on 2023-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_fileproject_sccom1_fileproject_sccom2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileproject',
            name='sccom1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='sccom2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='sccon',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
