# Generated by Django 4.1.7 on 2023-04-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_fileproject_sccom1_alter_fileproject_sccom2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='committee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com1', to='website.profmodel'),
        ),
        migrations.AddField(
            model_name='scoremodel',
            name='committee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com2', to='website.profmodel'),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='sccom1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='sccom2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='sccon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
