# Generated by Django 4.1.6 on 2023-03-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_projectmodel_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profmodel'),
        ),
    ]
