# Generated by Django 4.1.7 on 2023-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_scoremodel_committee1_scoremodel_committee2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproject',
            name='subscore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
