# Generated by Django 4.1.6 on 2023-03-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_projectmodel_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.profmodel')),
            ],
        ),
    ]
