# Generated by Django 4.1.7 on 2023-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_fileproject_subscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecom1',
            name='sc7',
        ),
        migrations.RemoveField(
            model_name='scorecom1',
            name='sc8',
        ),
        migrations.RemoveField(
            model_name='scorecom2',
            name='sc7',
        ),
        migrations.RemoveField(
            model_name='scorecom2',
            name='sc8',
        ),
        migrations.RemoveField(
            model_name='scoreconsult',
            name='sc7',
        ),
        migrations.RemoveField(
            model_name='scoreconsult',
            name='sc8',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='com1sc',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='com2sc',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='consc',
        ),
        migrations.AlterField(
            model_name='fileproject',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
