# Generated by Django 4.1.7 on 2023-04-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_fileproject_subscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremodel',
            name='com1sc',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='com2sc',
        ),
        migrations.RemoveField(
            model_name='scoremodel',
            name='consc',
        ),
    ]
