# Generated by Django 4.1.6 on 2023-03-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0016_coordinatormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatormodel',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
