# Generated by Django 4.1.7 on 2023-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_stdplanmodel_file_alter_docmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileproject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
